name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout test case
      uses: actions/checkout@v3
      with: 
        repository : ubsuny/WorldOfTextCraftInputsFall2022 
        ref: main
        path: './WorldOfTextCraftInputsFall2022'
    - name: make
      run: make
    - name: run
      run: |
        Start-Process ".\WorldOfTextCraft ThreeStooges.txt Shemp.txt ShempAttacks.txt" -RedirectStandardInput ".\WorldOfTextCraftInputsFall2022\problem1_inputs.txt" -NoNewWindow -Wait
      shell: cmd
